[Main]
Version=True
Theater=0
FalconDir=d:\Falcon BMS 4.38
FalconKey=4.38
Mission=
CamTeTrn=0
TE=-BMS5-001 Multinational War.tac
Camp=
UserName=3ggy
Country=0
Airport=0
Briefing=
DataCard=
Names=0,0,0,0
SaveLoc=True
ShowTooltips=True
Screen=1280x960
StartLocX=0
StartLocY=0
SelTheater=
DatacardDir=D:\Falcon BMS 4.38\User\Config\Backup\Weapon_Delivery_Planner_3.7.24.232\DataCards\
PrevObjDir=
TdfLoc=d:\Falcon BMS 4.38\Data\Terrdata\theaterdefinition\theater.lst
CallsignFile=
ATIS=True
KmSm=True
Timer=False
Side=1
SavePicSize=False
Recent0=
Recent1=
Recent2=
Recent3=
Recent4=
Recent5=
Recent6=
Recent7=
Recent8=
Recent9=
ATOexp=False
AutoLoadLastMission=False
KneeUpdater=False
HeliosNaming=False

[DTC]
CMDS = 0
HUD = 0
MasterArm = 0
Views = 0

[PopUp]
Input=False
Ref=False
Profile=True
Bomb=True
IngressAlt=100
DiveAngle=30
Cas=500
ReleaseHeight=5000
TrackingTime=5
PullingGs=3
Turn=1
AttackHdg=0
VIPtoPUP=3
OA2toAO=0
HighLow=Low
Direction=North
Waypoint=5
OA2atAO=0

[HADB]
Input=False
Version=True
Bomb=True
CAS=450
ReleaseHeight=12000
TrackingTime=5
DiveAngle=30
IngressCAS=350
PullingGs=3
Turn=Right
VRPtoPUP=3
AngleOff=60
AttackHdg=0
HighLow=60
Direction=North
Waypoint=5

[TOSS]
Input=False
Ref=False
Delivery=False
LAT=True
DiveAngle=0
IngressCAS=500
IngressHeight=1000
PullingGs=3
Turn=1
OA2toPUP=3
ReleaseAngle=30
ReleaseCAS=500
ReleaseHeight=4000
AngleOff=0
AttackHdg=0
Waypoint=5

[Performance]
Apt=
Rwy=
Temp=25
Type=9
Fuel=No Tank
Loadout=0
Drag =1.0
Pitch=13
Power=0
CruiseAlt=25000
TaxiFuel=200
[Map]
TextColor=0
Bullseye=0
WhiteMap=0
UseLargeMap=True
Airports=0
Strips=0
AirportsName=0
Vortac=0
Opacity=50
SA2=0
SA3=0
SA4=0
SA5=0
SA6=0
SA8=0
SA10=0
SA11=0
SA12=0
SA13=0
SA15=0
SA17=0
2S6=0
Chapparal=0
Crotale=0
Roland=0
SkyGuard=0
Nike=0
Hawk=0
Patriot=0
SearchRadar=0
SearchRadarLarge=0
[Datacard]
Swing=False
SetRange=2
Ews1=
Ews2=
Ews3=
Ews4=
Ews5=
Ews6=
Class1=
Class2=
Class3=
Class4=
Mtr1=
Mtr2=
Mtr3=
Mtr4=
Fr1=
Fr2=
Fr3=
Fr4=
Mar1=
Mar2=
Mar3=
Mar4=
Dr1=
Dr2=
Dr3=
Dr4=
Dor1=
Dor2=
Dor3=
Dor4=
[CommCard]
Swing=False
[Kneeboard]
KneeboardLastFile=
Left1=0
Left2=0
Left3=0
Left4=0
Left5=0
Left6=0
Left7=0
Left8=0
Left9=0
Left10=0
Left11=0
Left12=0
Left13=0
Left14=0
Left15=0
Left16=0
LeftFile1=
LeftFile2=
LeftFile3=
LeftFile4=
LeftFile5=
LeftFile6=
LeftFile7=
LeftFile8=
LeftFile9=
LeftFile10=
LeftFile11=
LeftFile12=
LeftFile13=
LeftFile14=
LeftFile15=
LeftFile16=
Right1=0
Right2=0
Right3=0
Right4=0
Right5=0
Right6=0
Right7=0
Right8=0
Right9=0
Right10=0
Right11=0
Right12=0
Right13=0
Right14=0
Right15=0
Right16=0
RightFile1=
RightFile2=
RightFile3=
RightFile4=
RightFile5=
RightFile6=
RightFile7=
RightFile8=
RightFile9=
RightFile10=
RightFile11=
RightFile12=
RightFile13=
RightFile14=
RightFile15=
RightFile16=
