[Main]
FalconDir=d:\Falcon BMS 4.38
FalconKey=4.38
Database=d:\Falcon BMS 4.38\data\Terrdata\objects\
DisableTerrain=False
ObjectiveColors=False
LastFile=Te_New.tac
LastTheatre=Korea
StartLocX=0
StartLocY=0
StartWidth=1541
StartHeight=1000
TacEditNaming=0
Recent0=D:\Falcon BMS 4.38\Data\Campaign\Te_New.tac
Recent1=D:\Falcon BMS 4.38\Data\Campaign\Bombing Test.tac
Recent2=
Recent3=
Recent4=
Recent5=
Recent6=
Recent7=
Recent8=
Recent9=
Recent10=
Recent11=
Recent12=
Recent13=
Recent14=
Recent15=
Recent16=
ImpExpDir=D:\Falcon BMS 4.38\User\Config\33 helpers\Mission_Commander_0.5.29.763\ImportExport\
ScaleMessage=False
YearOn=False
YearStart=1945
YearEnd=2100
ForceDenyFile=
UnitExportFile=
BrigadeSaveFile=
[Terrain]
TerrainGrid=0
ShowForest=False
ShowWater=False
ShiftListFile=
TerrainFlatFile=
[Previous]
MissionDir=
FalconDir=
FalconKey=
[Map]
Selection=1
MissionZoom=2.24898385093168
MissionX=951
MissionY=1605
ShowNames=1
MapTextColor=255, 255, 255
ShowAllObj=0
ShowAirports=0
ShowHighwayStrips=0
ShowArmyBase=0
ShowArmyBaseSubType=0
ShowBorder=0
ShowHarts=0
ShowFort=0
ShowDepot=0
ShowDepotSubType=0
ShowAirDefLoc=0
ShowAirDefSubType=0
ShowRadar=0
ShowChemical=0
ShowFactory=0
ShowRefinery=0
ShowBridge=0
ShowPowerPlant=0
ShowNuclearPlant=0
ShowCity=1
ShowTown=0
ShowVillage=0
ShowIntersection=0
ShowHilltop=0
ShowCCC=0
ShowRadioTower=0
ShowPort=0
ShowMaritimePatrol=0
ShowBeach=0
ShowVorTac=0
ShowAllAir=0
ShowAllLand=0
ShowAllSea=0
ShowSquadron=0
ShowFlight=0
ShowFighter=0
ShowAttack=0
ShowBomber=0
ShowAwacs=0
ShowTanker=0
ShowTransport=0
ShowRecon=0
ShowAsw=0
ShowAttackHeli=0
ShowHeli=0
ShowAirDefence=0
ShowSam=0
ShowAaa=0
ShowAirMobile=0
ShowArmor=0
ShowArmoredCav=0
ShowHq=0
ShowInfantry=0
ShowMarine=0
ShowMech=0
ShowMissile=0
ShowSpArt=0
ShowTowedArt=0
ShowRockets=0
ShowSupport=0
ShowEngineer=0
ShowAmphibious=0
ShowCarrier=0
ShowCruiser=0
ShowDestroyer=0
ShowFrigate=0
ShowPatrol=0
ShowSupply=0
ShowSeaTanker=0
ShowSeaTransport=0
RulerColor=0, 0, 0
LastUsedOwnMap=
[Objectives]
Details=0
